rails:
  build: .
  dockerfile: ./docker/Dockerfile-server
  ports:
   - "3000:3000"
  volumes:
   - .:/home/app/campusflora
  links:
   - mysql
mysql:
  build: .
  dockerfile: ./docker/Dockerfile-mysql
  volumes_from:
   - mysqldata
mysqldata:
  build: .
  dockerfile: ./docker/Dockerfile-mysql-data