rails:
  build: .
  dockerfile: ./docker/Dockerfile-server
  ports:
   - "80:80"
  volumes:
   - .:/home/app/campusflora
  links:
   - mysql
mysql:
  build: .
  dockerfile: ./docker/Dockerfile-mysql
  volumes_from:
   - mysqldata
  ports:
   - "3306:3306"
mysqldata:
  build: .
  dockerfile: ./docker/Dockerfile-mysql-data
